### PR TITLE
add backgrounding option to makefile

### PR DESCRIPTION
**Pull request by crclark96**
solution to #77 

open to clarification of use from @Corb3nik, this should provide a way to run the bot in the background, but the grammar can be changed to whatever feels more comfortable

### CODE REVIEW

**Comment by Corb3nik** [comment]
Seems interesting and way simpler than using tmux/python :D

What do you think @Kileak @Grazfather? I'm not too familiar with Makefiles, but is this the kind of approach we'd like for easy restarting/daemonizing?

**Comment by Grazfather** [comment]
looks good, but is `docker rm` necessary? We are running with `docker run --rm` which should kill the container automatically when we kill it.

**Comment by crclark96** [comment]
guess i overlooked that

fixed

**Comment by Kileak** [comment]
What happens to the console and the debug log in "background mode"?

**Comment by crclark96** [comment]
`docker logs otabot`

**Pull request merged**
