### PR TITLE
#161 - alias finishctf to take same action as endctf

### PR DESCRIPTION
**Pull request by drtychai**

### CODE REVIEW

**Comment by Grazfather** [comment]
Thanks!

**Comment by Kileak** [comment]
This is not really an "alias" but just duplicating the command.

Thus the command will now show up two times in the help and updating one command would not change the other command (bad for maintaining this).

If we want to have different aliases for the same command, we should add an alias functionality in the command descriptor itself but not just copy commands for every alias...

**Comment by Grazfather** [comment]
Yep, but let's just file a ticket for proper alias support.

**Comment by drtychai** [comment]
You're right kileak, I'll rework it and submit another PR when I have something more maintainable.

**Pull request merged**
